name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
        continue-on-error: true
      - name: Run unit tests
        run: python -m pytest --import-mode=append tests/

